#!/bin/bash -eu
set -o pipefail

TAG=$(grep tag operator.yaml | cut -d: -f2 | tr -d ' ')

docker run --rm \
  --network host \
  --volume "${HOME}/.kube/config:/kube-config:ro" \
  istio/istioctl:${TAG} \
    experimental create-remote-secret \
      --kubeconfig /kube-config \
      --name koala \
      $@
