apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "service-account-api-audiences": "api,vault,factors"
      "service-account-issuer": "api"
      "service-account-key-file": "/etc/kubernetes/pki/sa.pub"
      "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
nodes:
  - role: control-plane
    extraPortMappings:
      # istio ingressgateway.
      - containerPort: 31390
        hostPort: 8443
        listenAddress: 127.0.0.1
      # vault.
      # - containerPort: 31391
      #   hostPort: 8200
      #   listenAddress: 127.0.0.1
